version: '3'
services:
  reverseproxy:
    image: jwilder/nginx-proxy
    ports:
        - 80:80
        - 443:443
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        # - nginx_certs:/etc/nginx/certs:rw
    networks:
        - reverseproxy_default

networks:
    reverseproxy_default:
        external: true
