version: "3"
services:
    builder:
        build:
            context: builder/.
        volumes:
            - ..:/app
        ports:
            - 4200
        environment:
            - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.local
        networks:
            default_local:
                aliases:
                    - ${COMPOSE_PROJECT_NAME}.local
networks:
    default_local:
        external: true
