version: '3'
services:
  frontend-builder:
    image: docker.pkg.github.com/babeetlebum/reeder/reeder_frontend-builder:1.0.0
    volumes:
      - ../..:/app
    working_dir: /app/frontend
    ports:
      - 4200
      - 9876
    environment:
      - VIRTUAL_HOST=${COMPOSE_PROJECT_NAME}.local
    networks:
      default_local:
        aliases:
          - ${COMPOSE_PROJECT_NAME}.local
networks:
  default_local:
    external: true
