name:                         reeder
root:                         ./

parameters:
    four_panes_layout_v2:     &four_panes_layout_v2 b4ff,213x60,0,0[213x15,0,0,1,213x44,0,16[213x12,0,16{106x12,0,16,9,106x12,107,16,26},213x31,0,29,27]]

windows:
  - frontend:
      layout: *four_panes_layout_v2
      panes:
        - p1:
            - cd frontend/docker
            - cat github-public-token | docker login https://docker.pkg.github.com -u Babeetlebum --password-stdin
            - yarn run docker:up
        - p2:
            - cd frontend
            - sleep 20
            - yarn run docker:connect
            - clear
        - p3:
            - cd frontend
            - sleep 20
            - yarn run docker:connect
            - clear
        - p4:
            - cd frontend
            - clear
  - backend:
      layout: *four_panes_layout_v2
      panes:
        - p1:
            - cd backend/docker
            - clear
        - p2:
            - cd backend/docker
            - sleep 60
            - docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -ti --user=user reeder_server_1 sh
            - clear
        - p3:
            - cd backend/docker
            - sleep 60
            - docker exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -ti --user=user reeder_builder_1 bash
            - clear
        - p4:
            - cd backend/docker
            - clear
