version: 2.1
jobs:
  test-step:
    docker:
      - image: docker.pkg.github.com/babeetlebum/reeder/reeder_frontend-builder:1.0.0
        auth:
          username: $GITHUB_DOCKER_USERNAME
          password: $GITHUB_DOCKER_TOKEN
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cd frontend
            yarn
            yarn run prod
      - run:
          name: Test
          command: yarn run test --watch=false
      - run:
          name: Test Coverage
          command: yarn run test --code-coverage --watch=false

workflows:
    test-workflow:
      jobs:
        - test-step
