version: 2.1
jobs:
  test:
    docker:
      - image: docker.pkg.github.com/babeetlebum/reeder/reeder_frontend-builder:1.0.0
        auth:
          username: $GITHUB_DOCKER_USERNAME
          password: $GITHUB_DOCKER_TOKEN
    steps:
      - checkout
      - run:
        name: Test step
        command: |
          echo 'This is a test pipeline'
          cd frontend
          yarn run test
        
workflows:
    test-workflow:
      jobs:
        - test
