version: '3'
services:
  api:
    image: docker.pkg.github.com/babeetlebum/reeder/reeder_api:1.2
    ports:
      - 8080
    networks:
      - back_default
      - reverseproxy_default
    environment:
      VIRTUAL_HOST: api.${COMPOSE_PROJECT_NAME}.${SERVER_HOSTNAME}

networks:
  back_default:
    external: true
  reverseproxy_default:
    external: true
