#   gutenberg:
#         image: cwolff/gutenberg-http

version: "3"
services:

    db:
        image: mysql:8.0.19
        volumes:
            - ../db:/db
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: reeder
            MYSQL_USER: springuser
            MYSQL_PASSWORD: springuser
        networks:
            - reverseproxy_default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080
        environment:
            - VIRTUAL_HOST=db.${COMPOSE_PROJECT_NAME}.local
            - MYSQL_ROOT_PASSWORD=mysql
            - PMA_USERNAME=alfred
            - PMA_PASSWORD=kwak
        links:
            - db
        networks:
            - reverseproxy_default

networks:
    reverseproxy_default:
        external: true
